# Dataset parameters
dataset:
  # Stochastic
  # train_path: "./datasets/year-5min.csv"
  # eval_path: "./datasets/month-5min.csv"
  # Deterministic
  train_path: "./datasets/year-5min.csv"
  eval_path: "./datasets/month-5min.csv"
  time_columns:
    - "Minute"
    - "Hour" 
    - "DayOfWeek"
    - "DayOfMonth"
    - "Month"
    - "Year"
  n_smart_devices: 8
  n_users: 1
  time_step: 5  # minutes

# Data module parameters
datamodule:
  batch_size: 256
  sequence_len: 1
  num_workers: 4

# Model parameters
model:
  hidden_size: 128
  num_layers: 3

# Training parameters
training:
  keep_hidden_state: true
  max_epochs: 1
  learning_rate: 0.001

# Logging
logging:
  log_folder: "logs/"
